import { index, integer, jsonb, pgTable, text, timestamp } from "drizzle-orm/pg-core";

/**
 * Data model.
 *
 * `messages.parts` stores the AI SDK UIMessage `parts` array as JSONB —
 * text chunks AND tool invocations (inputs, outputs, per-call cost) in their
 * original order. This keeps replay exact (the UI re-renders history
 * identically to the live stream) without a brittle relational explosion of
 * tool-call tables. Costs are also denormalised onto the message row for
 * cheap aggregation.
 */

export const conversations = pgTable("conversations", {
  id: text("id").primaryKey(), // nanoid, generated by the app
  title: text("title").notNull().default("New conversation"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const messages = pgTable(
  "messages",
  {
    id: text("id").primaryKey(), // UIMessage id from the AI SDK
    conversationId: text("conversation_id")
      .notNull()
      .references(() => conversations.id, { onDelete: "cascade" }),
    role: text("role", { enum: ["user", "assistant", "system"] }).notNull(),
    parts: jsonb("parts").notNull(),
    /** Total Orthogonal spend attributed to this message, in cents. */
    costCents: integer("cost_cents").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("messages_conversation_idx").on(t.conversationId, t.createdAt)],
);
